apiVersion: manifest.k8s.io/v1alpha1
kind: Manifest
metadata:
  name: wordpress
# This is not using an persistent volume, but we ues empty dir.
# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#volume-v1-core
description: Wordpress Deployment using empty dir
resources:
- deployment.yaml
- service.yaml
